CREATE TABLE USER(
  USERNAME VARCHAR(40) PRIMARY KEY,
  PASSWORD  VARCHAR(10),
  ROLE VARCHAR(40),
  NAME VARCHAR(40),
  LASTNAME VARCHAR(40)
);
CREATE TABLE PACIENTE(
  NOME VARCHAR(40),
  DATA_NASC DATE,
  CPF VARCHAR(15) PRIMARY KEY
);
CREATE TABLE INTERNACAO(
  CPF VARCHAR(15),
  DATA_INTERN DATE,
  LEITO INT,
  POSTO INT,
  SETOR INT,
  MED_RESPONSAVEL VARCHAR(40),
  FOREIGN KEY(CPF) REFERENCES PACIENTE(CPF),
  FOREIGN KEY(MED_RESPONSAVEL) REFERENCES USER(USERNAME),
  PRIMARY KEY (CPF, DATA_INTERN)
);
CREATE TABLE MEDICAMENTO(
  ID INT PRIMARY KEY,
  NOME VARCHAR(40),

);
CREATE TABLE PRESCRICAO(
  ID INT PRIMARY KEY,
  CPF VARCHAR(15),
  USERNAME VARCHAR(40),
  ID_MEDICAMENTO INT,
  MED_RESPONSAVEL VARCHAR(40),
  FOREIGN KEY(CPF) REFERENCES PACIENTE(CPF),
  FOREIGN KEY(MED_RESPONSAVEL) REFERENCES USER(USERNAME),
);
CREATE TABLE MEDICAMENTO_PRESCRICAO(
  ID_MEDICAMENTO INT,
  ID_PRESCRICAO INT,
  PRIMARY KEY (ID_MEDICAMENTO, ID_PRESCRICAO),
  FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID),
  FOREIGN KEY (ID_PRESCRICAO) REFERENCES PRESCRICAO(ID)
);