CREATE TABLE USER(USERNAME VARCHAR(40) PRIMARY KEY, PASSWORD  VARCHAR(10));
CREATE TABLE PACIENTE(NOME VARCHAR(40), DATA_NASC DATE, DOCUMENTO VARCHAR(40) PRIMARY KEY);
CREATE TABLE INTERNACAO(DOCUMENTO VARCHAR(40), DATA_INTERN DATE, LEITO INT, POSTO INT, SETOR INT, FOREIGN KEY(DOCUMENTO) REFERENCES PACIENTE(DOCUMENTO));
CREATE TABLE MEDICAMENTO(ID INT PRIMARY KEY, NOME VARCHAR(40));
CREATE TABLE PRESCRICAO(ID INT PRIMARY KEY, DOCUMENTO VARCHAR(40), USERNAME VARCHAR(40, ID_MEDICAMENTO INT));